exclude: |
    (?x)(
        # 문서 파일
        ^.*\.md$|
        ^.*\.json$|
        ^docs/|

        # 노트북 및 실험 파일
        ^notebooks/|
        ^experiments/|
        ^wandb/|
        ^logs/|
        ^runs/|

        # 데이터 및 모델 파일
        ^data/|
        ^datasets/|
        ^checkpoints/|
        ^weights/|
        ^.*\.pth$|
        ^.*\.ckpt$|
        ^.*\.h5$|
        ^.*\.onnx$|

        # 캐시 및 생성 파일
        ^.pytest_cache/|
        ^__pycache__/|
        ^build/|
        ^dist/|
        ^.*\.egg-info/|

        # 기타 설정 파일
        ^\.env|
        ^\.venv/|
        ^venv/|
        ^\.idea/|
        ^\.vscode/
    )

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: check-added-large-files
        args: ['--maxkb=1024']


-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
