name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -e ".[dev]"

    - name: Lint with Ruff
      run: ruff check .

    - name: Run tests
      run: pytest tests/ --cov

    - name: Upload coverage
      uses: codecov/codecov-action@v3
