name: Validate N8N Workflow Images

on:
  push:
    branches: [ main, deployment ]
  pull_request:
    branches: [ main, deployment ]
    paths:
      - '.github/workflows/n8n/**.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for matching image files
        id: check-images
        shell: bash
        run: |
          # Find all JSON files in the n8n directory
          json_files=$(find .github/workflows/n8n -name "*.json")

          # Define supported image extensions
          declare -a image_extensions=("png" "PNG" "jpg" "JPG" "jpeg" "JPEG")

          # Initialize error flag
          error=0
          missing_files=""

          # Check each JSON file
          for json_file in $json_files; do
            # Get the base path without extension
            base_path="${json_file%.json}"

            # Initialize flag for current JSON file
            found_image=0

            # Check for each supported image extension
            for ext in "${image_extensions[@]}"; do
              if [ -f "${base_path}.${ext}" ]; then
                found_image=1
                break
              fi
            done

            # If no image was found for this JSON, add to missing files
            if [ $found_image -eq 0 ]; then
              error=1
              file_name="${json_file#.github/workflows/n8n/}"
              base_name="${file_name%.json}"
              missing_files="$missing_files\n- ${base_name} (needs one of: ${image_extensions[*]})"
            fi
          done

          # Set output and display results
          if [ $error -eq 1 ]; then
            echo "Missing image files for the following workflows:$missing_files"
            echo "status=failed" >> $GITHUB_OUTPUT
          else
            echo "All workflows have corresponding image files"
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Fail if images are missing
        if: steps.check-images.outputs.status == 'failed'
        shell: bash
        run: |
          echo "Error: Some workflow JSON files are missing their corresponding image files"
          exit 1
